server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri:  ${USERS_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/users/**
        - id: project-service
          uri:  ${PROJECTS_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/projects/**
        - id: planning-service
          uri:  ${PLANNING_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/plannings/**

management:
  endpoints:
    web:
      exposure:
        include: "health,info,gateway,metrics"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
